logging:
  file: testFile.log
  level:
    root: DEBUG
    sun.rmi: false
    org.springframework: false
    org.apache: false
    freemarker.cache: false
    org.hibernate: false
spring:
  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/payroll?useUnicode=true&characterEncoding=utf8
    username: payroll
    password: payroll
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    openInView: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        cache.use_second_level_cache: true
        cache.use_query_cache: false
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  basic:
    enabled: false